/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { partitionsDisableMcp } from "../../funcs/partitionsDisableMcp.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations.DisableMcpPartitionsPartitionIdMcpDeleteRequest$inboundSchema,
};

export const tool$partitionsDisableMcp: ToolDefinition<typeof args> = {
  name: "partitions-disable-mcp",
  description: `Disable Mcp

Disables context-aware descriptions for a partition. This will stop automatically generating descriptions for the partition.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await partitionsDisableMcp(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
