/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Documents } from "./documents.js";
import { Entities } from "./entities.js";
import { Retrievals } from "./retrievals.js";

export class Ragie extends ClientSDK {
    private _documents?: Documents;
    get documents(): Documents {
        return (this._documents ??= new Documents(this.options$));
    }

    private _retrievals?: Retrievals;
    get retrievals(): Retrievals {
        return (this._retrievals ??= new Retrievals(this.options$));
    }

    private _entities?: Entities;
    get entities(): Entities {
        return (this._entities ??= new Entities(this.options$));
    }
}
