/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the ragie SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx documentsCreate.ts
 */

import { openAsBlob } from "node:fs";
import { Ragie } from "ragie";

const ragie = new Ragie({
  auth: "<YOUR_BEARER_TOKEN_HERE>",
});

async function main() {
  const result = await ragie.create({
    file: await openAsBlob("example.file"),
  });

  console.log(result);
}

main().catch(console.error);
