workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    local:
        inputs:
            - location: https://7tzpsf3b-8000.use.devtunnels.ms/openapi.json
        registry:
            location: registry.speakeasyapi.dev/ragie-ai/ragie-ai/local
    ragie.ai_spec:
        inputs:
            - location: https://api.ragie.ai/openapi.json
        registry:
            location: registry.speakeasyapi.dev/ragie-ai/ragie-ai/ragie-ai-spec
targets:
    ragie:
        target: typescript
        source: local
        publish:
            npm:
                token: $npm_token
