/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type ListEntitiesByDocumentRequest = {
    documentId: string;
    /**
     * An opaque cursor for pagination
     */
    cursor?: string | null | undefined;
    /**
     * The number of items per page (must be greater than 0 and less than or equal to 100)
     */
    pageSize?: number | undefined;
};

/** @internal */
export const ListEntitiesByDocumentRequest$inboundSchema: z.ZodType<
    ListEntitiesByDocumentRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        document_id: z.string(),
        cursor: z.nullable(z.string()).optional(),
        page_size: z.number().int().default(10),
    })
    .transform((v) => {
        return remap$(v, {
            document_id: "documentId",
            page_size: "pageSize",
        });
    });

/** @internal */
export type ListEntitiesByDocumentRequest$Outbound = {
    document_id: string;
    cursor?: string | null | undefined;
    page_size: number;
};

/** @internal */
export const ListEntitiesByDocumentRequest$outboundSchema: z.ZodType<
    ListEntitiesByDocumentRequest$Outbound,
    z.ZodTypeDef,
    ListEntitiesByDocumentRequest
> = z
    .object({
        documentId: z.string(),
        cursor: z.nullable(z.string()).optional(),
        pageSize: z.number().int().default(10),
    })
    .transform((v) => {
        return remap$(v, {
            documentId: "document_id",
            pageSize: "page_size",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListEntitiesByDocumentRequest$ {
    /** @deprecated use `ListEntitiesByDocumentRequest$inboundSchema` instead. */
    export const inboundSchema = ListEntitiesByDocumentRequest$inboundSchema;
    /** @deprecated use `ListEntitiesByDocumentRequest$outboundSchema` instead. */
    export const outboundSchema = ListEntitiesByDocumentRequest$outboundSchema;
    /** @deprecated use `ListEntitiesByDocumentRequest$Outbound` instead. */
    export type Outbound = ListEntitiesByDocumentRequest$Outbound;
}
