/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListElementsRequest = {
  documentId: string;
  /**
   * An opaque cursor for pagination
   */
  cursor?: string | null | undefined;
  /**
   * The number of items per page (must be greater than 0 and less than or equal to 100)
   */
  pageSize?: number | undefined;
  type?: Array<components.DocumentElementType> | null | undefined;
  indexStart?: number | null | undefined;
  indexEnd?: number | null | undefined;
  /**
   * An optional partition to scope the request to. If omitted, accounts created after 1/9/2025 will have the request scoped to the default partition, while older accounts will have the request scoped to all partitions. Older accounts may opt in to strict partition scoping by contacting support@ragie.ai. Older accounts using the partitions feature are strongly recommended to scope the request to a partition.
   */
  partition?: string | null | undefined;
};

/** @internal */
export const ListElementsRequest$inboundSchema: z.ZodType<
  ListElementsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  document_id: z.string(),
  cursor: z.nullable(z.string()).optional(),
  page_size: z.number().int().default(10),
  type: z.nullable(z.array(components.DocumentElementType$inboundSchema))
    .optional(),
  index_start: z.nullable(z.number().int()).optional(),
  index_end: z.nullable(z.number().int()).optional(),
  partition: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "document_id": "documentId",
    "page_size": "pageSize",
    "index_start": "indexStart",
    "index_end": "indexEnd",
  });
});
/** @internal */
export type ListElementsRequest$Outbound = {
  document_id: string;
  cursor?: string | null | undefined;
  page_size: number;
  type?: Array<string> | null | undefined;
  index_start?: number | null | undefined;
  index_end?: number | null | undefined;
  partition?: string | null | undefined;
};

/** @internal */
export const ListElementsRequest$outboundSchema: z.ZodType<
  ListElementsRequest$Outbound,
  z.ZodTypeDef,
  ListElementsRequest
> = z.object({
  documentId: z.string(),
  cursor: z.nullable(z.string()).optional(),
  pageSize: z.number().int().default(10),
  type: z.nullable(z.array(components.DocumentElementType$outboundSchema))
    .optional(),
  indexStart: z.nullable(z.number().int()).optional(),
  indexEnd: z.nullable(z.number().int()).optional(),
  partition: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    documentId: "document_id",
    pageSize: "page_size",
    indexStart: "index_start",
    indexEnd: "index_end",
  });
});

export function listElementsRequestToJSON(
  listElementsRequest: ListElementsRequest,
): string {
  return JSON.stringify(
    ListElementsRequest$outboundSchema.parse(listElementsRequest),
  );
}
export function listElementsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListElementsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListElementsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListElementsRequest' from JSON`,
  );
}
