/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PatchInstructionRequest = {
  /**
   * The ID of the instruction.
   */
  instructionId: string;
  patchInstructionParams: components.PatchInstructionParams;
};

/** @internal */
export const PatchInstructionRequest$inboundSchema: z.ZodType<
  PatchInstructionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  instruction_id: z.string(),
  PatchInstructionParams: components.PatchInstructionParams$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "instruction_id": "instructionId",
    "PatchInstructionParams": "patchInstructionParams",
  });
});
/** @internal */
export type PatchInstructionRequest$Outbound = {
  instruction_id: string;
  PatchInstructionParams: components.PatchInstructionParams$Outbound;
};

/** @internal */
export const PatchInstructionRequest$outboundSchema: z.ZodType<
  PatchInstructionRequest$Outbound,
  z.ZodTypeDef,
  PatchInstructionRequest
> = z.object({
  instructionId: z.string(),
  patchInstructionParams: components.PatchInstructionParams$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    instructionId: "instruction_id",
    patchInstructionParams: "PatchInstructionParams",
  });
});

export function patchInstructionRequestToJSON(
  patchInstructionRequest: PatchInstructionRequest,
): string {
  return JSON.stringify(
    PatchInstructionRequest$outboundSchema.parse(patchInstructionRequest),
  );
}
export function patchInstructionRequestFromJSON(
  jsonString: string,
): SafeParseResult<PatchInstructionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchInstructionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchInstructionRequest' from JSON`,
  );
}
