/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Bibliography = {
  type?: "Bibliography" | undefined;
  /**
   * The text content of the bibliography.
   */
  content: string;
};

/** @internal */
export const Bibliography$inboundSchema: z.ZodType<
  Bibliography,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("Bibliography").default("Bibliography"),
  content: z.string(),
});
/** @internal */
export type Bibliography$Outbound = {
  type: "Bibliography";
  content: string;
};

/** @internal */
export const Bibliography$outboundSchema: z.ZodType<
  Bibliography$Outbound,
  z.ZodTypeDef,
  Bibliography
> = z.object({
  type: z.literal("Bibliography").default("Bibliography" as const),
  content: z.string(),
});

export function bibliographyToJSON(bibliography: Bibliography): string {
  return JSON.stringify(Bibliography$outboundSchema.parse(bibliography));
}
export function bibliographyFromJSON(
  jsonString: string,
): SafeParseResult<Bibliography, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Bibliography$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Bibliography' from JSON`,
  );
}
