/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Button = {
  type?: "Button" | undefined;
  /**
   * The text content inside the button
   */
  content: string;
};

/** @internal */
export const Button$inboundSchema: z.ZodType<Button, z.ZodTypeDef, unknown> = z
  .object({
    type: z.literal("Button").default("Button"),
    content: z.string(),
  });
/** @internal */
export type Button$Outbound = {
  type: "Button";
  content: string;
};

/** @internal */
export const Button$outboundSchema: z.ZodType<
  Button$Outbound,
  z.ZodTypeDef,
  Button
> = z.object({
  type: z.literal("Button").default("Button" as const),
  content: z.string(),
});

export function buttonToJSON(button: Button): string {
  return JSON.stringify(Button$outboundSchema.parse(button));
}
export function buttonFromJSON(
  jsonString: string,
): SafeParseResult<Button, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Button$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Button' from JSON`,
  );
}
