/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ConnectionSyncProgressWebhookPayload = {
  connectionId: string;
  syncId: string;
  partition: string;
  connectionMetadata: { [k: string]: any };
  createCount: number;
  createdCount: number;
  updateContentCount: number;
  updatedContentCount: number;
  updateMetadataCount: number;
  updatedMetadataCount: number;
  deleteCount: number;
  deletedCount: number;
  erroredCount: number;
};

/** @internal */
export const ConnectionSyncProgressWebhookPayload$inboundSchema: z.ZodType<
  ConnectionSyncProgressWebhookPayload,
  z.ZodTypeDef,
  unknown
> = z.object({
  connection_id: z.string(),
  sync_id: z.string(),
  partition: z.string(),
  connection_metadata: z.record(z.any()),
  create_count: z.number().int(),
  created_count: z.number().int(),
  update_content_count: z.number().int(),
  updated_content_count: z.number().int(),
  update_metadata_count: z.number().int(),
  updated_metadata_count: z.number().int(),
  delete_count: z.number().int(),
  deleted_count: z.number().int(),
  errored_count: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "connection_id": "connectionId",
    "sync_id": "syncId",
    "connection_metadata": "connectionMetadata",
    "create_count": "createCount",
    "created_count": "createdCount",
    "update_content_count": "updateContentCount",
    "updated_content_count": "updatedContentCount",
    "update_metadata_count": "updateMetadataCount",
    "updated_metadata_count": "updatedMetadataCount",
    "delete_count": "deleteCount",
    "deleted_count": "deletedCount",
    "errored_count": "erroredCount",
  });
});

/** @internal */
export type ConnectionSyncProgressWebhookPayload$Outbound = {
  connection_id: string;
  sync_id: string;
  partition: string;
  connection_metadata: { [k: string]: any };
  create_count: number;
  created_count: number;
  update_content_count: number;
  updated_content_count: number;
  update_metadata_count: number;
  updated_metadata_count: number;
  delete_count: number;
  deleted_count: number;
  errored_count: number;
};

/** @internal */
export const ConnectionSyncProgressWebhookPayload$outboundSchema: z.ZodType<
  ConnectionSyncProgressWebhookPayload$Outbound,
  z.ZodTypeDef,
  ConnectionSyncProgressWebhookPayload
> = z.object({
  connectionId: z.string(),
  syncId: z.string(),
  partition: z.string(),
  connectionMetadata: z.record(z.any()),
  createCount: z.number().int(),
  createdCount: z.number().int(),
  updateContentCount: z.number().int(),
  updatedContentCount: z.number().int(),
  updateMetadataCount: z.number().int(),
  updatedMetadataCount: z.number().int(),
  deleteCount: z.number().int(),
  deletedCount: z.number().int(),
  erroredCount: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    connectionId: "connection_id",
    syncId: "sync_id",
    connectionMetadata: "connection_metadata",
    createCount: "create_count",
    createdCount: "created_count",
    updateContentCount: "update_content_count",
    updatedContentCount: "updated_content_count",
    updateMetadataCount: "update_metadata_count",
    updatedMetadataCount: "updated_metadata_count",
    deleteCount: "delete_count",
    deletedCount: "deleted_count",
    erroredCount: "errored_count",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConnectionSyncProgressWebhookPayload$ {
  /** @deprecated use `ConnectionSyncProgressWebhookPayload$inboundSchema` instead. */
  export const inboundSchema =
    ConnectionSyncProgressWebhookPayload$inboundSchema;
  /** @deprecated use `ConnectionSyncProgressWebhookPayload$outboundSchema` instead. */
  export const outboundSchema =
    ConnectionSyncProgressWebhookPayload$outboundSchema;
  /** @deprecated use `ConnectionSyncProgressWebhookPayload$Outbound` instead. */
  export type Outbound = ConnectionSyncProgressWebhookPayload$Outbound;
}

export function connectionSyncProgressWebhookPayloadToJSON(
  connectionSyncProgressWebhookPayload: ConnectionSyncProgressWebhookPayload,
): string {
  return JSON.stringify(
    ConnectionSyncProgressWebhookPayload$outboundSchema.parse(
      connectionSyncProgressWebhookPayload,
    ),
  );
}

export function connectionSyncProgressWebhookPayloadFromJSON(
  jsonString: string,
): SafeParseResult<ConnectionSyncProgressWebhookPayload, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ConnectionSyncProgressWebhookPayload$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConnectionSyncProgressWebhookPayload' from JSON`,
  );
}
