/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreatePartitionParams = {
  name: string;
  pagesHostedLimitMonthly?: number | null | undefined;
  pagesProcessedLimitMonthly?: number | null | undefined;
  pagesHostedLimitMax?: number | null | undefined;
  pagesProcessedLimitMax?: number | null | undefined;
};

/** @internal */
export const CreatePartitionParams$inboundSchema: z.ZodType<
  CreatePartitionParams,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  pages_hosted_limit_monthly: z.nullable(z.number().int()).optional(),
  pages_processed_limit_monthly: z.nullable(z.number().int()).optional(),
  pages_hosted_limit_max: z.nullable(z.number().int()).optional(),
  pages_processed_limit_max: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    "pages_hosted_limit_monthly": "pagesHostedLimitMonthly",
    "pages_processed_limit_monthly": "pagesProcessedLimitMonthly",
    "pages_hosted_limit_max": "pagesHostedLimitMax",
    "pages_processed_limit_max": "pagesProcessedLimitMax",
  });
});

/** @internal */
export type CreatePartitionParams$Outbound = {
  name: string;
  pages_hosted_limit_monthly?: number | null | undefined;
  pages_processed_limit_monthly?: number | null | undefined;
  pages_hosted_limit_max?: number | null | undefined;
  pages_processed_limit_max?: number | null | undefined;
};

/** @internal */
export const CreatePartitionParams$outboundSchema: z.ZodType<
  CreatePartitionParams$Outbound,
  z.ZodTypeDef,
  CreatePartitionParams
> = z.object({
  name: z.string(),
  pagesHostedLimitMonthly: z.nullable(z.number().int()).optional(),
  pagesProcessedLimitMonthly: z.nullable(z.number().int()).optional(),
  pagesHostedLimitMax: z.nullable(z.number().int()).optional(),
  pagesProcessedLimitMax: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    pagesHostedLimitMonthly: "pages_hosted_limit_monthly",
    pagesProcessedLimitMonthly: "pages_processed_limit_monthly",
    pagesHostedLimitMax: "pages_hosted_limit_max",
    pagesProcessedLimitMax: "pages_processed_limit_max",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreatePartitionParams$ {
  /** @deprecated use `CreatePartitionParams$inboundSchema` instead. */
  export const inboundSchema = CreatePartitionParams$inboundSchema;
  /** @deprecated use `CreatePartitionParams$outboundSchema` instead. */
  export const outboundSchema = CreatePartitionParams$outboundSchema;
  /** @deprecated use `CreatePartitionParams$Outbound` instead. */
  export type Outbound = CreatePartitionParams$Outbound;
}

export function createPartitionParamsToJSON(
  createPartitionParams: CreatePartitionParams,
): string {
  return JSON.stringify(
    CreatePartitionParams$outboundSchema.parse(createPartitionParams),
  );
}

export function createPartitionParamsFromJSON(
  jsonString: string,
): SafeParseResult<CreatePartitionParams, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePartitionParams$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePartitionParams' from JSON`,
  );
}
