/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DefinitionList = {
  type?: "DefinitionList" | undefined;
  /**
   * The text content of the list and each item.
   */
  content: string;
};

/** @internal */
export const DefinitionList$inboundSchema: z.ZodType<
  DefinitionList,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("DefinitionList").default("DefinitionList"),
  content: z.string(),
});
/** @internal */
export type DefinitionList$Outbound = {
  type: "DefinitionList";
  content: string;
};

/** @internal */
export const DefinitionList$outboundSchema: z.ZodType<
  DefinitionList$Outbound,
  z.ZodTypeDef,
  DefinitionList
> = z.object({
  type: z.literal("DefinitionList").default("DefinitionList" as const),
  content: z.string(),
});

export function definitionListToJSON(definitionList: DefinitionList): string {
  return JSON.stringify(DefinitionList$outboundSchema.parse(definitionList));
}
export function definitionListFromJSON(
  jsonString: string,
): SafeParseResult<DefinitionList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DefinitionList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DefinitionList' from JSON`,
  );
}
