/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type DocumentDeleteWebhookPayloadMetadata = {};

export type DocumentDeleteWebhookPayload = {
  documentId: string;
  partition: string;
  metadata: DocumentDeleteWebhookPayloadMetadata;
  externalId: string | null;
  syncId: string | null;
};

/** @internal */
export const DocumentDeleteWebhookPayloadMetadata$inboundSchema: z.ZodType<
  DocumentDeleteWebhookPayloadMetadata,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type DocumentDeleteWebhookPayloadMetadata$Outbound = {};

/** @internal */
export const DocumentDeleteWebhookPayloadMetadata$outboundSchema: z.ZodType<
  DocumentDeleteWebhookPayloadMetadata$Outbound,
  z.ZodTypeDef,
  DocumentDeleteWebhookPayloadMetadata
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DocumentDeleteWebhookPayloadMetadata$ {
  /** @deprecated use `DocumentDeleteWebhookPayloadMetadata$inboundSchema` instead. */
  export const inboundSchema =
    DocumentDeleteWebhookPayloadMetadata$inboundSchema;
  /** @deprecated use `DocumentDeleteWebhookPayloadMetadata$outboundSchema` instead. */
  export const outboundSchema =
    DocumentDeleteWebhookPayloadMetadata$outboundSchema;
  /** @deprecated use `DocumentDeleteWebhookPayloadMetadata$Outbound` instead. */
  export type Outbound = DocumentDeleteWebhookPayloadMetadata$Outbound;
}

/** @internal */
export const DocumentDeleteWebhookPayload$inboundSchema: z.ZodType<
  DocumentDeleteWebhookPayload,
  z.ZodTypeDef,
  unknown
> = z.object({
  document_id: z.string(),
  partition: z.string(),
  metadata: z.lazy(() => DocumentDeleteWebhookPayloadMetadata$inboundSchema),
  external_id: z.nullable(z.string()),
  sync_id: z.nullable(z.string()),
}).transform((v) => {
  return remap$(v, {
    "document_id": "documentId",
    "external_id": "externalId",
    "sync_id": "syncId",
  });
});

/** @internal */
export type DocumentDeleteWebhookPayload$Outbound = {
  document_id: string;
  partition: string;
  metadata: DocumentDeleteWebhookPayloadMetadata$Outbound;
  external_id: string | null;
  sync_id: string | null;
};

/** @internal */
export const DocumentDeleteWebhookPayload$outboundSchema: z.ZodType<
  DocumentDeleteWebhookPayload$Outbound,
  z.ZodTypeDef,
  DocumentDeleteWebhookPayload
> = z.object({
  documentId: z.string(),
  partition: z.string(),
  metadata: z.lazy(() => DocumentDeleteWebhookPayloadMetadata$outboundSchema),
  externalId: z.nullable(z.string()),
  syncId: z.nullable(z.string()),
}).transform((v) => {
  return remap$(v, {
    documentId: "document_id",
    externalId: "external_id",
    syncId: "sync_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DocumentDeleteWebhookPayload$ {
  /** @deprecated use `DocumentDeleteWebhookPayload$inboundSchema` instead. */
  export const inboundSchema = DocumentDeleteWebhookPayload$inboundSchema;
  /** @deprecated use `DocumentDeleteWebhookPayload$outboundSchema` instead. */
  export const outboundSchema = DocumentDeleteWebhookPayload$outboundSchema;
  /** @deprecated use `DocumentDeleteWebhookPayload$Outbound` instead. */
  export type Outbound = DocumentDeleteWebhookPayload$Outbound;
}
