/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const DocumentElementType = {
  Caption: "Caption",
  Title: "Title",
  Text: "Text",
  UncategorizedText: "UncategorizedText",
  NarrativeText: "NarrativeText",
  Image: "Image",
  FigureCaption: "FigureCaption",
  TableCaption: "TableCaption",
  ListItem: "ListItem",
  Address: "Address",
  EmailAddress: "EmailAddress",
  PageBreak: "PageBreak",
  Formula: "Formula",
  Table: "Table",
  Header: "Header",
  Footer: "Footer",
  Json: "Json",
  AudioTranscriptionSegment: "AudioTranscriptionSegment",
  VideoSegment: "VideoSegment",
  SubHeader: "SubHeader",
  SectionHeader: "SectionHeader",
  Author: "Author",
  CalendarDate: "CalendarDate",
  Quote: "Quote",
  Comment: "Comment",
  UnorderedList: "UnorderedList",
  OrderedList: "OrderedList",
  DefinitionList: "DefinitionList",
  Figure: "Figure",
  Stamp: "Stamp",
  Logo: "Logo",
  Watermark: "Watermark",
  Barcode: "Barcode",
  QrCode: "QrCode",
  Signature: "Signature",
  KeyValue: "KeyValue",
  FormField: "FormField",
  Code: "Code",
  Bibliography: "Bibliography",
  TableOfContents: "TableOfContents",
  Footnote: "Footnote",
  Time: "Time",
  Button: "Button",
  Video: "Video",
} as const;
export type DocumentElementType = ClosedEnum<typeof DocumentElementType>;

/** @internal */
export const DocumentElementType$inboundSchema: z.ZodNativeEnum<
  typeof DocumentElementType
> = z.nativeEnum(DocumentElementType);
/** @internal */
export const DocumentElementType$outboundSchema: z.ZodNativeEnum<
  typeof DocumentElementType
> = DocumentElementType$inboundSchema;
