/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type FigureCaption = {
  type?: "FigureCaption" | undefined;
  /**
   * The text content
   */
  content: string;
};

/** @internal */
export const FigureCaption$inboundSchema: z.ZodType<
  FigureCaption,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("FigureCaption").default("FigureCaption"),
  content: z.string(),
});
/** @internal */
export type FigureCaption$Outbound = {
  type: "FigureCaption";
  content: string;
};

/** @internal */
export const FigureCaption$outboundSchema: z.ZodType<
  FigureCaption$Outbound,
  z.ZodTypeDef,
  FigureCaption
> = z.object({
  type: z.literal("FigureCaption").default("FigureCaption" as const),
  content: z.string(),
});

export function figureCaptionToJSON(figureCaption: FigureCaption): string {
  return JSON.stringify(FigureCaption$outboundSchema.parse(figureCaption));
}
export function figureCaptionFromJSON(
  jsonString: string,
): SafeParseResult<FigureCaption, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FigureCaption$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FigureCaption' from JSON`,
  );
}
