/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Header = {
  type?: "Header" | undefined;
  /**
   * The text content
   */
  content: string;
};

/** @internal */
export const Header$inboundSchema: z.ZodType<Header, z.ZodTypeDef, unknown> = z
  .object({
    type: z.literal("Header").default("Header"),
    content: z.string(),
  });
/** @internal */
export type Header$Outbound = {
  type: "Header";
  content: string;
};

/** @internal */
export const Header$outboundSchema: z.ZodType<
  Header$Outbound,
  z.ZodTypeDef,
  Header
> = z.object({
  type: z.literal("Header").default("Header" as const),
  content: z.string(),
});

export function headerToJSON(header: Header): string {
  return JSON.stringify(Header$outboundSchema.parse(header));
}
export function headerFromJSON(
  jsonString: string,
): SafeParseResult<Header, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Header$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Header' from JSON`,
  );
}
