/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Json = {
  type?: "Json" | undefined;
  /**
   * The text content
   */
  content: string;
};

/** @internal */
export const Json$inboundSchema: z.ZodType<Json, z.ZodTypeDef, unknown> = z
  .object({
    type: z.literal("Json").default("Json"),
    content: z.string(),
  });
/** @internal */
export type Json$Outbound = {
  type: "Json";
  content: string;
};

/** @internal */
export const Json$outboundSchema: z.ZodType<Json$Outbound, z.ZodTypeDef, Json> =
  z.object({
    type: z.literal("Json").default("Json" as const),
    content: z.string(),
  });

export function jsonToJSON(json: Json): string {
  return JSON.stringify(Json$outboundSchema.parse(json));
}
export function jsonFromJSON(
  jsonString: string,
): SafeParseResult<Json, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Json$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Json' from JSON`,
  );
}
