/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Time = {
  type?: "Time" | undefined;
  /**
   * The time text content
   */
  content: string;
};

/** @internal */
export const Time$inboundSchema: z.ZodType<Time, z.ZodTypeDef, unknown> = z
  .object({
    type: z.literal("Time").default("Time"),
    content: z.string(),
  });
/** @internal */
export type Time$Outbound = {
  type: "Time";
  content: string;
};

/** @internal */
export const Time$outboundSchema: z.ZodType<Time$Outbound, z.ZodTypeDef, Time> =
  z.object({
    type: z.literal("Time").default("Time" as const),
    content: z.string(),
  });

export function timeToJSON(time: Time): string {
  return JSON.stringify(Time$outboundSchema.parse(time));
}
export function timeFromJSON(
  jsonString: string,
): SafeParseResult<Time, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Time$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Time' from JSON`,
  );
}
