/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UncategorizedText = {
  /**
   * The text content
   */
  content: string;
};

/** @internal */
export const UncategorizedText$inboundSchema: z.ZodType<
  UncategorizedText,
  z.ZodTypeDef,
  unknown
> = z.object({
  content: z.string(),
});
/** @internal */
export type UncategorizedText$Outbound = {
  content: string;
};

/** @internal */
export const UncategorizedText$outboundSchema: z.ZodType<
  UncategorizedText$Outbound,
  z.ZodTypeDef,
  UncategorizedText
> = z.object({
  content: z.string(),
});

export function uncategorizedTextToJSON(
  uncategorizedText: UncategorizedText,
): string {
  return JSON.stringify(
    UncategorizedText$outboundSchema.parse(uncategorizedText),
  );
}
export function uncategorizedTextFromJSON(
  jsonString: string,
): SafeParseResult<UncategorizedText, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UncategorizedText$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UncategorizedText' from JSON`,
  );
}
