/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Video = {
  type?: "Video" | undefined;
  /**
   * A description of what the video shows.
   */
  content: string;
};

/** @internal */
export const Video$inboundSchema: z.ZodType<Video, z.ZodTypeDef, unknown> = z
  .object({
    type: z.literal("Video").default("Video"),
    content: z.string(),
  });
/** @internal */
export type Video$Outbound = {
  type: "Video";
  content: string;
};

/** @internal */
export const Video$outboundSchema: z.ZodType<
  Video$Outbound,
  z.ZodTypeDef,
  Video
> = z.object({
  type: z.literal("Video").default("Video" as const),
  content: z.string(),
});

export function videoToJSON(video: Video): string {
  return JSON.stringify(Video$outboundSchema.parse(video));
}
export function videoFromJSON(
  jsonString: string,
): SafeParseResult<Video, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Video$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Video' from JSON`,
  );
}
