/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type WordModality = {
  word: string;
  probability: number;
  start: number;
  end: number;
};

/** @internal */
export const WordModality$inboundSchema: z.ZodType<
  WordModality,
  z.ZodTypeDef,
  unknown
> = z.object({
  word: z.string(),
  probability: z.number(),
  start: z.number(),
  end: z.number(),
});
/** @internal */
export type WordModality$Outbound = {
  word: string;
  probability: number;
  start: number;
  end: number;
};

/** @internal */
export const WordModality$outboundSchema: z.ZodType<
  WordModality$Outbound,
  z.ZodTypeDef,
  WordModality
> = z.object({
  word: z.string(),
  probability: z.number(),
  start: z.number(),
  end: z.number(),
});

export function wordModalityToJSON(wordModality: WordModality): string {
  return JSON.stringify(WordModality$outboundSchema.parse(wordModality));
}
export function wordModalityFromJSON(
  jsonString: string,
): SafeParseResult<WordModality, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WordModality$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WordModality' from JSON`,
  );
}
